import "./globals.css";
import NavBar from "./components/navbar";
import Footer from "./components/footer";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Tilux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="min-h-screen flex flex-col">
        {/* Toast notifications handler */}
        <Toaster position="top-center" reverseOrder={false} />
        
        <header className="sticky top-0 z-50">
          <NavBar />
        </header>

        <main className="flex-grow">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}